# Author      : Luis Merino Troncoso
# Date        : 20/06/2021
# Description : Certified Kubernetes Administrator Labs ( CNCF )
#               Certificates : Signing request
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  signerName: kubernetes.io/kube-apiserver-client
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXk5cGxtK3B0Q0MwODVmSXc1aklBM1JHcFRGcWE2a0ltNlB3M1U2citnU2F3CjVTRU03aFQ3bFUrM3pHT05oRE85TEUwWVBBVVN1dzJSeXpCbmp4aU9wY0tzZFpST2NSMFlQSzkvUlladjdxVXoKekNPSWkyTklpMWRFKzVRVld1VDVaSzdORmlvYkoxZm92ZUJnOVlFQncrY1ZORUpmc2k4TE53anh4TS9rT3dvNgpFMzE3U0hnbkNvdDRqRlpDSmRYWktBdlBBUmtub2RvU21RM0VxSGx3NjdHajFPT3dJT2Y1RnFLQ0pveWFPVHBaCk5RQWpWVXpsVjdJUFMwRStxMHc5NVdXRllhaElsaG5hVHM1bG4wRjc5endldzdQb09LY1RBS2EyR2JKS3Z5NkcKOUh0ODFFa2dDVW5XMzdsVDFHdFZHRnZHcUl3bDNHR3RVejJwK0IrUVV3SURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBTDRYT2llY0h1NzRNWHBjYkFKMU5vTWJrWEE3aDB5cC93NWFLOGk5TktsZTU0OVkzN2hVCkNkYnFoL0RNL3BzUUxGR21XdWt4NWNXKzJIZzVVemgwYVpNQkQ0QWJUM2drSjFXWHlqV3YyL01tL2JIMVptVHkKVzR6R0RtQWlDcE9OQi8vNzBpdy9NeXJWT1JESzVyMW52RDhsZk5iNXZLcGtHazRhMVlnaitxcmpTRDZNUUFGMwprMXN4UlZOS0dqc1Uya3NTZnhmTXlva1BITkUvak9VcGpPVzFqUVdqTjFieGwveXJRbVBvOExWVWJwS0Y2cy9SCkZadUFGYjJKOEhocHNCbWVXSERKVUVya2kxWUtxQmlJVmdmU004RjRscUtpZDVqRkZ6S0I3N0Y0VHNkK2poUzYKSWxoNzFxVkR0N3BZL3BzRWZHeXNOSjFpVC9ydXhzSWtRNlE9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:
  - digital signature
  - key encipherment
  - server auth