# Author      : Luis Merino Troncoso
# Date        : 14/07/2021
# Description : Certified Kubernetes Administrator Labs ( CNCF )
#               Cluster Role Binding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-role-node-bind
subjects:
- kind: User
  name: michelle
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: Cluster-role-nodes
  apiGroup: rbac.authorization.k8s.io