# Author      : Luis Merino Troncoso
# Date        : 20/06/2021
# Description : Certified Kubernetes Administrator Labs ( CNCF )
#               Secrets
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_Host: c3FsMDEK
  DB_User: cm9vdAo=
  DB_Password: cGFzc3dvcmQxMjMK