# Author      : Luis Merino Troncoso
# Date        : 08/07/2021
# Description : Certified Kubernetes Administrator Labs ( CNCF )
#               InitCointainers
apiVersion: v1
kind: Pod
metadata:
  name: red
  namespace: default
spec:
  containers:
  - command:
    - sh
    - -c
    - echo The app is running! && sleep 3600
    image: busybox:1.28
    name: red-container
  initContainers:
  - name: init-myservice
    image: busybox
    command: ["sleep", "20"]