# Author      : Luis Merino Troncoso
# Date        : 22/06/2021
# Description : Certified Kubernetes Administrator Labs ( CNCF )
#               Storage - Dynamic Provisioning -Persistent Volume Claims with storage classes 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName:  local-storage