# Author      : Luis Merino Troncoso
# Date        : 20/06/2021
# Description : Certified Kubernetes Administrator Labs ( CNCF )
#               roles & roleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list","create","delete"]