# Author      : Luis Merino Troncoso
# Date        : 05/07/2021
# Description : Certified Kubernetes Administrator Labs ( CNCF )
#               Env Variables 
apiVersion: v1
kind: Pod
metatdata:
  name: webapp-pod
spec:
  containers:
  - name: webapp
    image: kodekloud/simple-webapp-mysql
    envFrom:
    - secretRef:
        name: app-secret