# Author      : Luis Merino Troncoso
# Date        : 05/07/2021
# Description : Certified Kubernetes Administrator Labs ( CNCF )
#               PODS
apiVersion: v1
kind: Pod
metadata:
  name: yellow
spec:
  containers:
  - name: lemon
    image: busybox
  - name: gold
    image: redis   